name: Java Lint via Reusable Workflow example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    uses: bhuva123/code-quality-reusable/.github/workflows/reusable-code-lint.yml@main
