name: Java Lint via Reusable Workflow test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  security-events: write

jobs:
  lint:
    uses: bhuva123/code-quality-reusable/.github/workflows/reusable-code-lint.yml@main
